# Generated by Django 3.2.8 on 2021-10-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_data_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
